<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>talepplanlama</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Abp.EntityFrameworkCore" Version="8.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.*" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\talepplanlama.Core\talepplanlama.Core.csproj" />
  </ItemGroup>
</Project>
