<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>talepplanlama</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Abp.AspNetCore" Version="8.*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.*" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\talepplanlama.Application\talepplanlama.Application.csproj" />
    <ProjectReference Include="..\talepplanlama.EntityFrameworkCore\talepplanlama.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
